name: Micronaut CRUD CI/CD

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: mn_playground
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done

      - name: Verify MySQL connection
        run: mysql -h"127.0.0.1" -P"3306" -uroot -ppassword -e "SHOW DATABASES;"

      - name: Build and Test
        run: ./gradlew build
        env:
          DATASOURCES_DEFAULT_URL: jdbc:mysql://localhost:3306/mn_playground
          DATASOURCES_DEFAULT_USERNAME: root
          DATASOURCES_DEFAULT_PASSWORD: password

      - name: Upload JAR as Build Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: micronaut-crud-app
          path: build/libs/*.jar